swagger: '2.0'
info:
  version: 1.0.0
  title: positivery
  description: positivery web api
schemes:
  - http
host: dev.positivery:8080
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  /hello:
    get:
      operationId: api.hello.get
      responses:
        200:
          description: simple hello
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
            example:
              message: hello
