swagger: '2.0'
info:
  version: 1.0.0
  title: positively
schemes:
  - http
host: dev.positively:8080
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  /hello:
    get:
      operationId: api.hello.get
      responses:
        200:
          description: simple hello
